#!/bin/bash
set -e
set -x

# Configs root directories
ASSETS='/tmp/assets'

apt-get update
apt-get install -y nginx php-fpm

# Remove the default page
rm /etc/nginx/sites-enabled/default

# Setup and enable php5-fpm
sed -i 's/cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/7.0/fpm/php.ini

mkdir -p /etc/service/php5-fpm
cat > /etc/service/php5-fpm/run <<PHP_RUN_SCRIPT
#!/bin/bash
set -e

exec /usr/sbin/php5-fpm -F --fpm-config /etc/php5/fpm/php-fpm.conf
PHP_RUN_SCRIPT
chmod +x /etc/service/php5-fpm/run

# Add my public key. Remember to remove this section if you're not me :)
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLx7ISCVMSReb+chT8Z33x3EOwYeqKKeLqell+mMSqT6lOqIhVz4btBExpDYk46M3GcctU/3lSgpI+bY1KqtCv6zknsvMRrHRXfziNfZYYAHvM7gv7DetRzG4ngipui0lqPEtti5aDriEbElK2b544i7twVYMk2Jt/P16I6hVRYitBoa4iNBLMEF1I6dkldRXr85tj0O3CnKkiyhyWvtSyvww9HxOAh1SuUfNAvxkoUoOXuszPmAJPUuTCFoRq9MsuhtvjJ3BflKAaQ3DTZTEXUxCDJnIlggLvUDlWWGK0BLj3nIhrsLpDVC8aN+ENRK6x7bWxerWdUlse5OV+yfog+7CamfkUNjStYL0Z/tCWYgqMzg0/MMALJeJAWSoZlsKHY7CO3DSwc40nRlY0/4tsEYoRvo+0NhnSNs0YaB9lNDBtxZv23+IsCE0OnoJRow85F3iJtIYFbSb+rnS216iPHI6ftrFQbmL/8pH2dNxvItV7YeyoEHKhaPENoS3uyiBloo+UyvptKLEsYE5mz4n7Esy8aj/HMGeuV56EQIPuYzU6fWqMufJSDvG5cyRsYCG+QAK3PNJrDyRdbjxHYetFkPty+zlaUKDr4XVxUzskM1S2TfYsWOqf/v2uVhHcu/ENt7iRefA1bwq/5sP3KXR2iNypyY/mFppb1GZ3mAuT1Q== smwood4@gmail.com' > /root/.ssh/authorized_keys

WEB_HOME='/var/www'

# ping.heystephenwood.com
mkdir -p ${WEB_HOME}/ping.heystephenwood.com
cp -r -- ${ASSETS}/vhosts/ping.heystephenwood.com/public_html ${WEB_HOME}/ping.heystephenwood.com/
cp -- ${ASSETS}/vhosts/ping.heystephenwood.com/ping_heystephenwood_com.conf /etc/nginx/conf.d/

# eth0.me
mkdir -p ${WEB_HOME}/eth0.me
cp -r -- ${ASSETS}/vhosts/eth0.me/public_html ${WEB_HOME}/eth0.me/
cp -- ${ASSETS}/vhosts/eth0.me/eth0_me.conf /etc/nginx/conf.d/

# Make nginx run in foreground (important for using runit) and also turn the worker processes down to 1
sed -i '1s/^/daemon off;/' /etc/nginx/nginx.conf
sed -i 's/worker_processes.*$/worker_processes 1;/' /etc/nginx/nginx.conf

# Add the runit script
test -d /etc/service/nginx || mkdir -p /etc/service/nginx
cat > /etc/service/nginx/run <<RUN
#!/bin/bash
set -e

exec /usr/sbin/nginx -q
RUN

# runit will execute this script to start the webserver
chmod +x /etc/service/nginx/run

# Make sure www-data can only read and execute files
chown -R nobody.www-data /var/www
chmod -R 550 /var/www

